# This is a basic workflow that publishes the website
name: Publish

# Controls when the action will run.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    name: Build and publishes the website to S3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.8' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
        
    - name: Install dependencies
      run: |
        sudo apt install git curl autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev
        
    - name: Bundle install
      run: |
        gem i bundler && bundle install

    - name: Build pages
      run: |
         bundle exec jekyll build

    - uses: actions/upload-pages-artifact

    - uses: actions/deploy-pages
